### ISSUE TITLE
not working on macos x

### ISSUE THREAD

**Issue by Fraer** [bytedeco/sbt-javacv#20]
Added the addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.17")

Got 

Caused by: java.lang.UnsatisfiedLinkError: no opencv_java343 in java.library.path

when calling 

System.loadLibrary(Core.NATIVE_LIBRARY_NAME)

**Comment by saudet** [comment]
Don't call that, call `Loader.load(opencv_java.class)` instead as mentioned here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by cupuyc** [comment]
Right, `Loader.load(classOf[opencv_java])` worked for me.
