### ISSUE TITLE
Getting an error trying to include ffmpeg

### ISSUE THREAD

**Issue by DaveDeCaprio** [bytedeco/sbt-javacv#9]
when I add this line to my build.sbt 
    javaCppPresetLibs ++= Seq("ffmpeg" -> "2.8.1")

I get this error refreshing the sbt project:
[error](*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: org.bytedeco.javacpp-presets#ffmpeg;2.8.1-1.2: not found
[error] Total time: 5 s, completed Sep 29, 2016 4:35:35 PM</pre><br/>See complete log in <a href="C:\Users\Dave\.IntelliJIdea2016.2\system\log\sbt.last.log">C:\Users\Dave.IntelliJIdea2016.2\system\log\sbt.last.log</a>

**Comment by saudet** [comment]
Try 3.1.2-1.2 instead

**Comment by lloydmeta** [comment]
Yep, you'll need to use 3.1.2 instead because version 2.8.1 is tied to an older version of JavaCPP (1.1) and we're on 1.2.x.

Try the following:

``` scala
javaCppPresetLibs ++= Seq("ffmpeg" -> "3.1.2")
javaCppVersion := "1.2.4" // <- not strictly necessary, a good idea to get the latest version.
```

**Comment by lloydmeta** [comment]
Closing now, as I am fairly sure the above solution works. If not please reopen !

**Comment by DaveDeCaprio** [comment]
Yup, works.

Dave
